In [1]:
## Carga de librerías

In [2]:
import pandas as pd

In [3]:
df_a = pd.read_csv("./ds/citasmedicas.csv")
df_p = pd.read_csv("./ds/pacientes.csv")

/tmp/ipykernel_806/3986461510.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_p = pd.read_csv("./ds/pacientes.csv")

In [4]:
df_a.shape

(7021, 11)

In [5]:
df_p.shape

(719973, 13)

In [6]:
df_a.head()

,idCita,idPac,fechaCita,nombreUsr,primerApellidoUsr,segundoApellidoUsr,fechaHoraElaboracion,estatusCita,lugRealizacion,ubicacion,especialidad
0,1068560,117096,2032-01-05 10:00:00,ALEJANDRO ALFONSO,MORAL,NARANJO,2022-10-11 11:27:24,Agendada,ALERGOLOGIA C1 - DR. GANDHI,NaN,INMUNOGENÉTICA Y ALERGIA
1,1069399,150583,2033-01-13 09:00:00,ANDREA,JUAREZ,MENDIETA,2022-10-13 10:32:18,Cancelada,GERIATRÍA SEGUIMIENTO SARS-COV-2,NaN,SUBDIRECCIÓN DE ATENCIÓN MÉDICA
2,1071766,130297,2032-01-12 10:00:00,ALEJANDRO ALFONSO,MORAL,NARANJO,2022-10-19 11:39:39,Agendada,ALERGOLOGIA C1 - DR. GANDHI,NaN,INMUNOGENÉTICA Y ALERGIA
3,1071865,117973,2032-01-28 10:00:00,ALEJANDRO ALFONSO,MORAL,NARANJO,2022-10-19 12:41:18,Agendada,ALERGOLOGIA E INMUNOLOGIA C1,NaN,INMUNOGENÉTICA Y ALERGIA
4,1213097,518444,2034-01-26 10:30:00,LAURA,ROSAS,AGUILAR,2023-10-26 13:28:08,Cancelada,DR. GUSTAVO IVAN CENTENO SAENZ,NaN,INVESTIGACIÓN EN TABAQUISMO Y EPOC

In [7]:
df_p.head()

,idPac,numExpediente,nomPaciente,primerApellido,segundoApellido,sexo,fechaNacimiento,curp,descConvenio,nivelSE,derHab,excentoPago,tipoDificultad
0,-3,SN0000002,SN,SN,SN,FEMENINO,2012-01-01,NaN,NaN,4.0,NINGUNO,Si,SE IGNORA
1,-2,SN0000001,SN,SN,SN,FEMENINO,1990-01-01,XEXX010101MNEXXXA8,NaN,1.0,IMSS,No,ESCUCHAR
2,-1,SN0000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NINGUNO,Si,SE IGNORA
3,1,000028567,BLANDINA,HERNANDEZ,PAREDES,FEMENINO,1930-06-02,NaN,NaN,5.0,NaN,No,SE IGNORA
4,2,000028878,FRANCISCO,ARIZA,BRAVO,MASCULINO,1959-09-27,NaN,NaN,5.0,NaN,No,SE IGNORA

In [8]:
df_p.columns

Index(['idPac', 'numExpediente', 'nomPaciente', 'primerApellido',
       'segundoApellido', 'sexo', 'fechaNacimiento', 'curp', 'descConvenio',
       'nivelSE', 'derHab', 'excentoPago', 'tipoDificultad'],
      dtype='object')

In [9]:
df_a.columns.values

array(['idCita', 'idPac', 'fechaCita', 'nombreUsr', 'primerApellidoUsr',
       'segundoApellidoUsr', 'fechaHoraElaboracion', 'estatusCita',
       'lugRealizacion', 'ubicacion', 'especialidad'], dtype=object)

In [10]:
df_p["name"] = df_p["nomPaciente"] + " " + df_p["primerApellido"] + " " + df_p["segundoApellido"]

In [11]:
patient_columns = ["idPac", "numExpediente", "name", "tipoDificultad"]

In [14]:
patient = df_p[patient_columns]
patient.columns = ["id", "file", "name", "disability"]
patient.head()

   id       file                        name disability
0  -3  SN0000002                    SN SN SN  SE IGNORA
1  -2  SN0000001                    SN SN SN   ESCUCHAR
2  -1  SN0000000                         NaN  SE IGNORA
3   1  000028567  BLANDINA HERNANDEZ PAREDES  SE IGNORA
4   2  000028878       FRANCISCO ARIZA BRAVO  SE IGNORA

In [15]:
patient["disability"].unique().tolist()

['SE IGNORA',
 'ESCUCHAR',
 'NINGUNA',
 'CAMINAR',
 'VER',
 'HABLAR/COMUNICARSE',
 'EMOCIONAL/MENTAL',
 'USAR BRAZOS/MANOS',
 'CUIDADO PERSONAL',
 'APRENDER/RECORDAR']