In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandasai import SmartDataframe
from pandasai import SmartDatalake
from pandasai import Agent
from langchain_groq.chat_models import ChatGroq

In [2]:
df_hq = pd.read_csv("./ds/Procedimiento1Hojadequirofano_20250424_utf-8.csv")
df_np = pd.read_csv("./ds/Procedimiento2NotaPostoperatoria_20250424_utf-8.csv")
df_hi = pd.read_csv("./ds/Procedimiento3Hojadeintervencionismo_20250424_utf-8.csv")

## Ajustar los datos de la Hoja de quirófano

In [3]:
df_hq.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      float64
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Cirugía realizada - CIE 9 Tratamientos - Clave                                           object
Cirugía realizada - CIE 9 Tratamientos - Descripción                                     object
Clave                                                                                    object
Descripción                                                                              object
dtype: object

In [4]:
df_hq = df_hq.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Cirugía realizada - CIE 9 Tratamientos - Clave',
                              'Cirugía realizada - CIE 9 Tratamientos - Descripción'])

In [5]:
df_hq.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Ajustar datos de la Nota postoperatoria

In [6]:
df_np.dtypes

ID Módulo Base                                                                           int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)              object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)     object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)    object
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento                       object
Fecha y Hora Registro                                                                   object
Fecha y Hora de Egreso                                                                  object
Fecha y hora de Elaboración                                                             object
Tipo de Ingreso                                                                         object
Hospitalizado en                                                                        object
Cirugía Realizada                                                                       object
Clave                                                                                   object
Descripción                                                                             object
dtype: object

In [7]:
df_np = df_np.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Fecha de nacimiento',
                              'Cirugía Realizada'])

In [8]:
df_np.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Ajustar datos de la Hoja de intervencionismo

In [9]:
df_hi.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                       object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Procedimiento realizado - CIE 9 Tratamientos - Clave                                    float64
Procedimiento realizado - CIE 9 Tratamientos - Descripción                               object
Clave                                                                                   float64
Descripción                                                                              object
dtype: object

In [10]:
df_hi = df_hi.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Procedimiento realizado - CIE 9 Tratamientos - Clave',
                              'Procedimiento realizado - CIE 9 Tratamientos - Descripción'])

In [11]:
df_hi.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Descripción

In [12]:
print("Datos en hoja de quirofano:",df_hq.shape[0])
print("Datos en hoja de intervencionismo:",df_hi.shape[0])
print("Datos en nota postoperatoria:",df_np.shape[0])
print("Datos HQ + HI:",df_hq.shape[0]+df_hi.shape[0])

Datos en hoja de quirofano: 271
Datos en hoja de intervencionismo: 898
Datos en nota postoperatoria: 1000
Datos HQ + HI: 1169

In [13]:
df_hq = df_hq.dropna(subset="Expediente")
df_hi = df_hi.dropna(subset="Expediente")
df_np = df_np.dropna(subset="Expediente")

In [14]:
print("Datos en hoja de quirofano:",df_hq.shape[0])
print("Datos en hoja de intervencionismo:",df_hi.shape[0])
print("Datos en nota postoperatoria:",df_np.shape[0])
print("Datos HQ + HI:",df_hq.shape[0]+df_hi.shape[0])

Datos en hoja de quirofano: 266
Datos en hoja de intervencionismo: 898
Datos en nota postoperatoria: 1000
Datos HQ + HI: 1164

In [15]:
print(df_np["Clave"].value_counts())

Clave
3142    82
2188    80
3322    45
2187    37
215     32
        ..
3429     1
00G5     1
7        1
348      1
5122     1
Name: count, Length: 220, dtype: int64

In [16]:
df_np.describe().transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82

In [17]:
df_hq.describe(include='object').transpose()

            count unique                     top freq
Registro      266    261                            4
Egreso        266    261                            4
Elaboracion   266    266      30.Nov.23 11:20:00    1
TipoIngreso   266      3  ADMISIÓN HOSPITALARIA   186
Servicio      266     13     Servicio Clínico 8   126
Clave          91     26                    2188   16
Descripcion    91     24       Otra septoplastia   16

In [18]:
df_np.describe(include='object').transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82

In [19]:
df_hi.describe(include='object').transpose()

            count unique                         top freq
Expediente    898    621                      210636   13
Registro      898    728                              134
Egreso        898    720                              144
Elaboracion   898    893          18.Sep.23 11:30:00    2
TipoIngreso   898      4  PROCEDIMIENTO AMBULATORIO   542
Servicio      898     14            Hospital de Día   330
Descripcion   701     24    Broncoscopia fibroóptica  551

## LLM

In [20]:
from dotenv import load_dotenv
load_dotenv()
llm = ChatGroq(model_name="llama3-70b-8192")

df_hq = SmartDataframe(df_hq, config={"llm": llm})
df_hi = SmartDataframe(df_hi, config={"llm": llm})
df_np = SmartDataframe(df_np, config={"llm": llm})

df = SmartDatalake([df_hq, df_hi, df_np], config={"llm": llm})

In [21]:
ai = Agent([df_hq, df_hi, df_np], config={"llm": llm}, memory_size=10)

In [22]:
ai.chat("¿Cuántos Expedientes repetidos existen?")

930

In [23]:
ai.chat("¿Cuántos registros coinciden en Expediente y Registro? Ponlos en una tabla")

    Expediente            Registro
0     245209.0  04.Jun.23 15:36:02
1     245209.0  04.Jun.23 15:36:02
2     251556.0  20.Jun.23 13:56:25
3     251556.0  20.Jun.23 13:56:25
4       162156  17.Abr.23 15:30:39
..         ...                 ...
481     254458  23.Nov.23 01:07:53
482      87987  15.May.23 15:10:51
483      87987  15.May.23 15:10:51
484  SN0000001  02.Oct.23 08:46:45
485  SN0000001  02.Oct.23 08:46:45

[486 rows x 2 columns]

In [24]:
ai.chat("Crea un dataframe llamado df a partir de la tabla anterior")

,Expediente,Registro,Egreso,Elaboracion,TipoIngreso,Servicio,Clave,Descripcion
0,248277.0,11.Ene.23 15:33:18,12.Ene.23 19:02:22,12.Ene.23 09:40:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,NaN,NaN
1,236422.0,11.Ene.23 15:48:18,12.Ene.23 19:05:18,12.Ene.23 08:41:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,NaN,NaN
2,209000.0,10.Ene.23 15:32:44,12.Ene.23 13:12:16,11.Ene.23 09:52:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,195,Otra timpanoplastia
3,243590.0,10.Ene.23 15:23:31,11.Ene.23 18:02:14,11.Ene.23 10:56:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,NaN,NaN
4,248153.0,11.Ene.23 09:40:52,11.Ene.23 15:29:00,11.Ene.23 13:24:00,PROCEDIMIENTO AMBULATORIO,Quirófanos,3322,Broncoscopia fibroóptica
...,...,...,...,...,...,...,...,...
2159,254692,24.Nov.23 01:43:36,22.Dic.23 17:12:51,01.Dic.23 16:20:38,ADMISIÓN HOSPITALARIA,Servicio Clínico 1,3406,Drenaje de cavidad pleural por toracoscopía
2160,221315,01.Dic.23 06:48:57,01.Dic.23 16:47:31,01.Dic.23 16:35:17,PROCEDIMIENTO AMBULATORIO,Hospital de Día,3322,Broncoscopia fibroóptica
2161,246005,01.Dic.23 07:47:57,03.Dic.23 09:24:55,01.Dic.23 17:49:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,3142,Laringoscopia y otra traqueoscopia
2162,253871,30.Nov.23 15:32:50,02.Dic.23 11:53:39,01.Dic.23 18:17:40,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,2122,Biopsia de nariz
2163,250693,06.Nov.23 18:18:13,16.Dic.23 18:00:56,02.Dic.23 14:30:46,ADMISIÓN HOSPITALARIA,Servicio Clínico 9,5122,Colecistectomía

In [25]:
df = ai.chat("Ordena df por Registro y muéstramelo")

In [26]:
df

,Expediente,Registro,Egreso,Elaboracion,TipoIngreso,Servicio,Clave,Descripcion
1209,244787,,,07.Mar.23 11:01:09,,,2187,Otra rinoplastia
1774,214147,,,25.Sep.23 21:11:59,,,311,Traqueostomía temporal
533,242200,,,10.Abr.23 12:24:00,,,3322.0,Broncoscopia fibroóptica
1759,242873,,,23.Sep.23 18:22:00,,,3323,Otra broncoscopia
704,251010,,,31.May.23 11:18:00,,,3322.0,Broncoscopia fibroóptica
...,...,...,...,...,...,...,...,...
1991,254171,31.Oct.23 11:19:58,16.Nov.23 17:33:03,06.Nov.23 12:02:43,ADMISIÓN HOSPITALARIA,Servicio Clínico 2,339,Otras operaciones sobre pulmón y bronquio
1990,254171,31.Oct.23 11:19:58,16.Nov.23 17:33:03,06.Nov.23 12:02:43,ADMISIÓN HOSPITALARIA,Servicio Clínico 2,332,Procedimientos diagnósticos sobre pulmón y bro...
1968,249742,31.Oct.23 15:21:45,01.Nov.23 17:35:24,01.Nov.23 10:58:11,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,2188,Otra septoplastia
1961,224936,31.Oct.23 17:06:07,10.Nov.23 13:18:24,31.Oct.23 14:12:46,INGRESO A TERAPIA,Servicio Clínico 2,3323,Otra broncoscopia
1964,242716,31.Oct.23 19:42:49,03.Nov.23 19:06:42,31.Oct.23 17:29:58,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,3129,Otra traqueostomía permanente