## Libraries

In [1]:
import pandas as pd

## Load data

In [2]:
df_a = pd.read_csv("./ds/citasmedicas.csv")
df_p = pd.read_csv("./ds/pacientes.csv")

/tmp/ipykernel_1575/3986461510.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_p = pd.read_csv("./ds/pacientes.csv")

## Patient table

In [3]:
df_p.columns

Index(['idPac', 'numExpediente', 'nomPaciente', 'primerApellido',
       'segundoApellido', 'sexo', 'fechaNacimiento', 'curp', 'descConvenio',
       'nivelSE', 'derHab', 'excentoPago', 'tipoDificultad'],
      dtype='object')

In [4]:
patient_columns = ["idPac", "numExpediente"]

In [5]:
patient = df_p.loc[3:, patient_columns]
patient.columns = ["id", "file"]

In [6]:
patient["name"] = df_p.loc[3:, "nomPaciente"].fillna('') + " " + df_p.loc[3:, "primerApellido"].fillna('') + " " + df_p.loc[3:, "segundoApellido"].fillna('')

In [7]:
df_p["tipoDificultad"].unique().tolist()

['SE IGNORA',
 'ESCUCHAR',
 'NINGUNA',
 'CAMINAR',
 'VER',
 'HABLAR/COMUNICARSE',
 'EMOCIONAL/MENTAL',
 'USAR BRAZOS/MANOS',
 'CUIDADO PERSONAL',
 'APRENDER/RECORDAR']

In [8]:
def disability_to_dummy(x):
    if (x == "NINGUNA" or
        x == "SE IGNORA"):
        return 0
    else:
        return 1

In [9]:
patient["disability"] = df_p.loc[3:, "tipoDificultad"].map(disability_to_dummy)
patient.tail(10)

            id       file                                name  disability
719963  720556  000268575  ANGEL ALAN MATIAS CAMACHO SANDOVAL           0
719964  720557  000268578                 FERNANDO CRUZ SALAS           1
719965  720558  000268576                    TOMAS FRANCISCO            1
719966  720559  IAN807813       CARLA ANAID SANCHEZ SANTILLAN           0
719967  720560  IAN807814                  ARTURO NIVON ZAGHI           0
719968  720561  IAN807815     MARIA LUISA ESPINDOLA ESPINDOLA           0
719969  720562  IAN807816                   SARA PEREZ IBARRA           0
719970  720563  IAN807817                 ALONSO PIÑA RAMIREZ           0
719971  720564  IAN807818           GRACIELA GARCIA HERNANDEZ           0
719972  720565  IAN807819            JORGE OMAR REYES ROSALES           0

In [10]:
df_p.tail(10)

,idPac,numExpediente,nomPaciente,primerApellido,segundoApellido,sexo,fechaNacimiento,curp,descConvenio,nivelSE,derHab,excentoPago,tipoDificultad
719963,720556,000268575,ANGEL ALAN MATIAS,CAMACHO,SANDOVAL,MASCULINO,2024-03-25,CASA240325HDFMNNA4,NaN,2.0,NINGUNO,Si,NINGUNA
719964,720557,000268578,FERNANDO,CRUZ,SALAS,MASCULINO,1973-05-30,CUSF730530HDFRLR01,NaN,3.0,NINGUNO,Si,VER
719965,720558,000268576,TOMAS,FRANCISCO,NaN,MASCULINO,1957-11-09,FAXT571109HOCRXM06,NaN,1.0,NINGUNO,Si,ESCUCHAR
719966,720559,IAN807813,CARLA ANAID,SANCHEZ,SANTILLAN,FEMENINO,2000-09-26,SASC000926MDFNNRA3,NaN,5.0,NaN,No,SE IGNORA
719967,720560,IAN807814,ARTURO,NIVON,ZAGHI,MASCULINO,1958-04-15,NIZA580415HDFVGR06,NaN,5.0,NaN,Si,SE IGNORA
719968,720561,IAN807815,MARIA LUISA,ESPINDOLA,ESPINDOLA,FEMENINO,1957-08-21,EIEL570821MHGSSS06,NaN,5.0,NaN,Si,SE IGNORA
719969,720562,IAN807816,SARA,PEREZ,IBARRA,FEMENINO,1959-11-22,PEIS591122MDFRBR08,NaN,5.0,NaN,Si,SE IGNORA
719970,720563,IAN807817,ALONSO,PIÑA,RAMIREZ,MASCULINO,2012-05-22,PIRA120522MDFXMLA7,NaN,5.0,NaN,Si,SE IGNORA
719971,720564,IAN807818,GRACIELA,GARCIA,HERNANDEZ,FEMENINO,1953-08-08,GAHG530808MMNRRR07,NaN,5.0,NaN,Si,SE IGNORA
719972,720565,IAN807819,JORGE OMAR,REYES,ROSALES,MASCULINO,2000-02-26,RERJ000226HDFYSRB5,NaN,5.0,NaN,Si,SE IGNORA

## Appointment table

In [11]:
df_a.columns.values

array(['idCita', 'idPac', 'fechaCita', 'nombreUsr', 'primerApellidoUsr',
       'segundoApellidoUsr', 'fechaHoraElaboracion', 'estatusCita',
       'lugRealizacion', 'ubicacion', 'especialidad'], dtype=object)